### ISSUE TITLE
Stratify With Fake Root

### ISSUE THREAD

**Issue by emeeks** [d3/d3-hierarchy#106] opened 2018-01-16 16:33 UTC
Is it possible for stratify to recognize when a network has multiple root nodes but is otherwise a hierarchical network? Say I send an edge list where the only hierarchical rules violation is that there are multiple roots, could stratify just return a fake root with children being all the valid roots stratify discovers?

**Comment by robodude** [comment] 2018-02-21 03:30
I had the same situation... I just manually created a 'fake' root node that had an appropriate parent id

**Comment by mbostock** [comment] 2019-10-22 16:23
This feels like a duplicate of #105. Having a loose version of d3.stratify would be fine on an opt-in basis. Currently the way to opt-in is to define the fake root explicitly, but you could submit a PR that allows this to be done automatically if configured.

**Closed by mbostock** 2019-10-22 16:23 UTC
